CREATE TABLE Pessoa (
    
   id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   nome VARCHAR(255) NOT NULL,
   idade INT(3) NOT NULL
);

CREATE TABLE Endereco (
   id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   rua VARCHAR(255) NOT NULL,
   cidade VARCHAR(100)
);
CREATE TABLE Telefones (
   id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   numero VARCHAR(20) NOT NULL,
   tipo VARCHAR(50)
);

CREATE TABLE Pedidos (
   id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   descricao VARCHAR(255) NOT NULL,
   valor DECIMAL(10,2) NOT NULL 
);

